"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_fg1 = '#ebdbb2'
color_bg0 = '#282828'
color_bg1 = '#3c3836'
color_bg2 = '#504945'
color_bg3 = '#665c54'
color_blue = '#83a598'
color_aqua = '#8ec07c'
color_green = '#b8bb26'
color_orange = '#fe8019'
color_purple = '#d3869b'
color_red = '#fb4934'
color_yellow = '#fabd2f'

[username]
show_always = true
style_user = "bold fg:color_blue"
style_root = "bold fg:color_yellow"
format = '[\[](bold fg:color_fg1)[$user]($style)'

[hostname]
ssh_only = false
style = "bold fg:color_orange"
format = '[[@](bold fg:color_fg1)$ssh_symbol$hostname]($style)[\]](bold fg:color_fg1)'

[directory]
style = "bold fg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 15
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bold fg:color_aqua"
format = '[[ $symbol $branch ](bold fg:color_aqua)]($style)'

[git_status]
style = "bold fg:color_aqua"
format = '[[($all_status$ahead_behind )](bold fg:color_aqua)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bold fg:color_purple"
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ❯](bold fg:color_green)'
error_symbol = '[ ❯](bold fg:color_red)'
vimcmd_symbol = '[ ❮](bold fg:color_yellow)'
